/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSetupRouteImport } from './routes/_auth/setup'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppUploadRouteImport } from './routes/_app/upload'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppBooksIdRouteImport } from './routes/_app/books/$id'
import { Route as AppBooksIdReadRouteImport } from './routes/_app/books/$id_.read'
import { Route as AppShelvesIdRouteImport } from './routes/_app/shelves/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksIdRoute = AppBooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksIdReadRoute = AppBooksIdReadRouteImport.update({
  id: '/books/$id_/read',
  path: '/books/$id/read',
  getParentRoute: () => AppRoute,
} as any)
const AppShelvesIdRoute = AppShelvesIdRouteImport.update({
  id: '/shelves/$id',
  path: '/shelves/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/upload': typeof AppUploadRoute
  '/search': typeof AppSearchRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/setup': typeof AuthSetupRoute
  '/books/$id': typeof AppBooksIdRoute
  '/books/$id/read': typeof AppBooksIdReadRoute
  '/shelves/$id': typeof AppShelvesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/upload': typeof AppUploadRoute
  '/search': typeof AppSearchRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/setup': typeof AuthSetupRoute
  '/books/$id': typeof AppBooksIdRoute
  '/books/$id/read': typeof AppBooksIdReadRoute
  '/shelves/$id': typeof AppShelvesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/upload': typeof AppUploadRoute
  '/_app/search': typeof AppSearchRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/setup': typeof AuthSetupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/books/$id': typeof AppBooksIdRoute
  '/_app/books/$id_/read': typeof AppBooksIdReadRoute
  '/_app/shelves/$id': typeof AppShelvesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/upload'
    | '/search'
    | '/login'
    | '/register'
    | '/setup'
    | '/books/$id'
    | '/books/$id/read'
    | '/shelves/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/upload'
    | '/search'
    | '/login'
    | '/register'
    | '/setup'
    | '/books/$id'
    | '/books/$id/read'
    | '/shelves/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/upload'
    | '/_app/search'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/setup'
    | '/_app/'
    | '/_app/books/$id'
    | '/_app/books/$id_/read'
    | '/_app/shelves/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/$id': {
      id: '/_app/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof AppBooksIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/$id_/read': {
      id: '/_app/books/$id_/read'
      path: '/books/$id/read'
      fullPath: '/books/$id/read'
      preLoaderRoute: typeof AppBooksIdReadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shelves/$id': {
      id: '/_app/shelves/$id'
      path: '/shelves/$id'
      fullPath: '/shelves/$id'
      preLoaderRoute: typeof AppShelvesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppUploadRoute: typeof AppUploadRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBooksIdRoute: typeof AppBooksIdRoute
  AppBooksIdReadRoute: typeof AppBooksIdReadRoute
  AppShelvesIdRoute: typeof AppShelvesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppUploadRoute: AppUploadRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppBooksIdRoute: AppBooksIdRoute,
  AppBooksIdReadRoute: AppBooksIdReadRoute,
  AppShelvesIdRoute: AppShelvesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSetupRoute: typeof AuthSetupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSetupRoute: AuthSetupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
